### PR TITLE
Fix bug with token validation and add error messages for webrequests

### PR DESCRIPTION
**Pull request by saus32**
Fix bug where token validation check always returned true.
+Add more Error messages on WebRequest to ease debugging 
+Set Mock4Core to be included only in Editor

### CODE REVIEW

**Review by MathiasMustonen — APPROVED** [review]
Jee Jee

**Comment by saus32** [comment]
Improved test cases

**Review by MathiasMustonen — APPROVED** [review]

**Review by MathiasMustonen — APPROVED** [review]
Jee Jee

**Review by sweet-and-salty-studios — APPROVED** [review]
Jee Jee

**Pull request merged**
